package yi

const (
	ENV_YI_ENDPOINT    = "YI_ENDPOINT"
	ENV_YI_API_VER     = "YI_API_VER"
	ENV_YI_MODEL_ALIAS = "YI_MODEL_ALIAS"
	ENV_YI_API_KEY     = "YI_API_KEY"
	ENV_YI_MODEL       = "YI_MODEL"

	ENV_YI_HTTP_PROXY  = "YI_HTTP_PROXY"
	ENV_YI_SOCKS_PROXY = "YI_SOCKS_PROXY"
)

const (
	DEFAULT_YI_API_VER = "2023-12-15-preview"
	DEFAULT_YI_MODEL   = "yi-34b-chat"
)
