package azure

const (
	ENV_AZURE_ENDPOINT    = "AZURE_ENDPOINT"
	ENV_AZURE_API_VER     = "AZURE_API_VER"
	ENV_AZURE_MODEL_ALIAS = "AZURE_MODEL_ALIAS"
	ENV_AZURE_API_KEY     = "AZURE_API_KEY"
	ENV_AZURE_MODEL       = "AZURE_MODEL"

	ENV_AZURE_HTTP_PROXY  = "AZURE_HTTP_PROXY"
	ENV_AZURE_SOCKS_PROXY = "AZURE_SOCKS_PROXY"
)

const (
	DEFAULT_AZURE_API_VER = "2023-05-15"
	DEFAULT_AZURE_MODEL   = "gpt-3.5-turbo"
)
